"use client";

import { useState, useEffect } from "react";
import { Search, Check, Copy, Info, ChevronDown, ChevronUp, Terminal } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { Separator } from "@/components/ui/separator";
import Script from "next/script";

interface Tweak {
  id: string;
  title: string;
  description: string;
  category: string[];
  recommended: boolean;
  reversible: boolean;
  docsurl?: string;
  source?: string;
  scripts: {
    apply: string;
    unapply?: string;
  };
}

interface TweakData {
  version: string;
  tweaks: Tweak[];
}

const CATEGORIES = ["General", "Appearance", "Performance", "Privacy", "Gaming", "Network", "GPU", "Maintenance"];

export default function TweaksPage() {
  const [tweaks, setTweaks] = useState<Tweak[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedTweaks, setSelectedTweaks] = useState<Set<string>>(new Set());
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedCategories, setSelectedCategories] = useState<Set<string>>(new Set());
  const [expandedCategories, setExpandedCategories] = useState<Set<string>>(new Set(CATEGORIES));
  const [generatedScript, setGeneratedScript] = useState("");
  const [showUnapply, setShowUnapply] = useState(false);

  useEffect(() => {
    fetchTweaks();
  }, []);

  const fetchTweaks = async () => {
    try {
      const response = await fetch("https://raw.githubusercontent.com/parcoil/sparkle/refs/heads/v2/tweaks/registry-scripts.json");
      const data: TweakData = await response.json();
      setTweaks(data.tweaks || []);
    } catch (error) {
      console.error("Failed to fetch tweaks:", error);
      toast.error("Failed to load tweaks");
    } finally {
      setLoading(false);
    }
  };

  const toggleTweak = (tweakId: string) => {
    const newSelected = new Set(selectedTweaks);
    if (newSelected.has(tweakId)) {
      newSelected.delete(tweakId);
    } else {
      newSelected.add(tweakId);
    }
    setSelectedTweaks(newSelected);
  };

  const toggleCategory = (category: string) => {
    const newCategories = new Set(selectedCategories);
    if (newCategories.has(category)) {
      newCategories.delete(category);
    } else {
      newCategories.add(category);
    }
    setSelectedCategories(newCategories);
  };

  const toggleExpandedCategory = (category: string) => {
    const newExpanded = new Set(expandedCategories);
    if (newExpanded.has(category)) {
      newExpanded.delete(category);
    } else {
      newExpanded.add(category);
    }
    setExpandedCategories(newExpanded);
  };

  const selectAllInCategory = (category: string) => {
    const categoryTweaks = getFilteredTweaks().filter(t => t.category.includes(category));
    const newSelected = new Set(selectedTweaks);
    categoryTweaks.forEach(t => newSelected.add(t.id));
    setSelectedTweaks(newSelected);
  };

  const deselectAllInCategory = (category: string) => {
    const categoryTweaks = getFilteredTweaks().filter(t => t.category.includes(category));
    const newSelected = new Set(selectedTweaks);
    categoryTweaks.forEach(t => newSelected.delete(t.id));
    setSelectedTweaks(newSelected);
  };

  const generateScript = () => {
    const selected = tweaks.filter(t => selectedTweaks.has(t.id));
    if (selected.length === 0) {
      setGeneratedScript("# No tweaks selected. Select tweaks above to generate a script.");
      return;
    }

    const scriptLines = [
      "# Sparkle Tweaks Script",
      "# Generated by getsparkle.net",
      "# Run as Administrator",
      "",
      "# Tweaks to apply:",
      ...selected.map(t => `# - ${t.title} (${t.id})`),
      "",
    ];

    if (showUnapply) {
      scriptLines.push("# Unapply scripts (to undo tweaks)");
      selected.forEach(tweak => {
        if (tweak.scripts.unapply) {
          scriptLines.push("");
          scriptLines.push(`# --- ${tweak.title} ---`);
          scriptLines.push(tweak.scripts.unapply);
        }
      });
    } else {
      scriptLines.push("# Apply scripts");
      selected.forEach(tweak => {
        scriptLines.push("");
        scriptLines.push(`# --- ${tweak.title} ---`);
        scriptLines.push(tweak.scripts.apply);
      });
    }

    setGeneratedScript(scriptLines.join("\n"));
  };

  useEffect(() => {
    generateScript();
  }, [selectedTweaks, showUnapply]);

  const copyScript = () => {
    if (!generatedScript) return;
    navigator.clipboard.writeText(generatedScript);
    toast.success("Script copied to clipboard");
  };

  const getFilteredTweaks = () => {
    return tweaks.filter(tweak => {
      const matchesSearch = tweak.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
                           tweak.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
                           tweak.id.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesCategory = selectedCategories.size === 0 ||
                              tweak.category.some(c => selectedCategories.has(c));
      return matchesSearch && matchesCategory;
    });
  };

  const getTweaksByCategory = () => {
    const filtered = getFilteredTweaks();
    const byCategory: Record<string, Tweak[]> = {};
    CATEGORIES.forEach(cat => byCategory[cat] = []);
    filtered.forEach(tweak => {
      tweak.category.forEach(cat => {
        if (byCategory[cat]) {
          byCategory[cat].push(tweak);
        }
      });
    });
    return byCategory;
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto"></div>
          <p className="mt-4 text-muted-foreground">Loading tweaks...</p>
        </div>
      </div>
    );
  }

  const byCategory = getTweaksByCategory();

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold tracking-tight">System Tweaks</h1>
          <p className="text-muted-foreground mt-2">
            Select tweaks to optimize your Windows system. Generate and run PowerShell scripts.
          </p>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 space-y-6">
            <div className="flex flex-col sm:flex-row gap-4">
              <div className="relative flex-1">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search tweaks..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-9"
                />
              </div>
              <div className="flex gap-2 flex-wrap">
                {CATEGORIES.map(category => (
                  <Badge
                    key={category}
                    variant={selectedCategories.has(category) ? "default" : "outline"}
                    className="cursor-pointer"
                    onClick={() => toggleCategory(category)}
                  >
                    {category}
                  </Badge>
                ))}
              </div>
            </div>

            <div className="space-y-4">
              {CATEGORIES.map(category => {
                const categoryTweaks = byCategory[category];
                if (categoryTweaks.length === 0) return null;

                return (
                  <Card key={category}>
                    <CardHeader className="pb-2">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => toggleExpandedCategory(category)}
                          >
                            {expandedCategories.has(category) ? (
                              <ChevronUp className="h-4 w-4" />
                            ) : (
                              <ChevronDown className="h-4 w-4" />
                            )}
                          </Button>
                          <CardTitle className="text-lg">{category}</CardTitle>
                          <Badge variant="secondary">{categoryTweaks.length}</Badge>
                        </div>
                        <div className="flex gap-2">
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => selectAllInCategory(category)}
                          >
                            Select All
                          </Button>
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => deselectAllInCategory(category)}
                          >
                            Deselect All
                          </Button>
                        </div>
                      </div>
                    </CardHeader>
                    {expandedCategories.has(category) && (
                      <CardContent className="space-y-3 pt-2">
                        {categoryTweaks.map(tweak => (
                          <div
                            key={tweak.id}
                            className={`flex items-start gap-3 p-3 rounded-lg border transition-colors ${
                              selectedTweaks.has(tweak.id)
                                ? "border-primary bg-primary/5"
                                : "border-border hover:bg-muted/50"
                            }`}
                          >
                            <Checkbox
                              checked={selectedTweaks.has(tweak.id)}
                              onCheckedChange={() => toggleTweak(tweak.id)}
                              className="mt-1"
                            />
                            <div className="flex-1 min-w-0">
                              <div className="flex items-center gap-2 flex-wrap">
                                <h3 className="font-medium">{tweak.title}</h3>
                                {tweak.recommended && (
                                  <Badge variant="default" className="text-xs">Recommended</Badge>
                                )}
                                {!tweak.reversible && (
                                  <Badge variant="destructive" className="text-xs">Not Reversible</Badge>
                                )}
                              </div>
                              <p className="text-sm text-muted-foreground mt-1">{tweak.description}</p>
                              <div className="flex gap-1 mt-2 flex-wrap">
                                {tweak.category.map(cat => (
                                  <Badge key={cat} variant="outline" className="text-xs">{cat}</Badge>
                                ))}
                              </div>
                            </div>
                          </div>
                        ))}
                      </CardContent>
                    )}
                  </Card>
                );
              })}
            </div>
          </div>

          <div className="space-y-6">
            <Card className="sticky top-4">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Terminal className="h-5 w-5" />
                  Generated Script
                </CardTitle>
                <CardDescription>
                  {selectedTweaks.size} tweak{selectedTweaks.size !== 1 ? "s" : ""} selected
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between">
                  <label className="text-sm font-medium">Show unapply scripts</label>
                  <Checkbox
                    checked={showUnapply}
                    onCheckedChange={(checked) => setShowUnapply(checked as boolean)}
                  />
                </div>

                <div className="h-64 overflow-auto rounded-md border bg-muted/50 p-4">
                  <pre className="text-xs font-mono whitespace-pre-wrap text-muted-foreground">
                    {generatedScript}
                  </pre>
                </div>

                <div className="flex gap-2">
                  <Button onClick={copyScript} className="flex-1" disabled={!generatedScript}>
                    <Copy className="h-4 w-4 mr-2" />
                    Copy Script
                  </Button>
                </div>

                <Separator />

                <div className="text-sm text-muted-foreground">
                  <p className="font-medium mb-2">How to use:</p>
                  <ol className="list-decimal list-inside space-y-1">
                    <li>Copy the PowerShell script</li>
                    <li>Open PowerShell as Administrator</li>
                    <li>Paste and run the script</li>
                  </ol>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Info className="h-5 w-5" />
                  Info
                </CardTitle>
              </CardHeader>
              <CardContent className="text-sm text-muted-foreground space-y-2">
                <p>All scripts require Administrator privileges.</p>
                <p>Reversible tweaks can be undone by regenerating the script with "Show unapply scripts" enabled.</p>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
      <Script
        async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1565760898646999"
        crossOrigin="anonymous"
      />
    </div>
  );
}
